# Installs `brew services` commands
tap 'homebrew/services'

# Provides alternate versions of casks
tap 'caskroom/versions'

# Dependencies
cask 'java'
cask 'xquartz'

cask 'android-file-transfer'
cask 'appcleaner'
brew 'awscli'
brew 'bfg'
cask 'chefdk'
cask 'colloquy'
brew 'coreutils'
cask 'cyberduck'
cask 'flux'
brew 'git'
brew 'gnu-sed'
cask 'google-drive'
cask 'google-chrome'
brew 'htop'
cask 'iterm2'
brew 'jq'
cask 'kitematic'
brew 'mtr'
brew 'nmap'
brew 'packer'
brew 'pssh'
brew 'pwgen'
brew 'python3'
brew 'rbenv'
brew 'rename'
brew 'ruby-build'
brew 'shellcheck'
brew 'squid'
cask 'sublime-text3'
brew 'the_silver_searcher'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
brew 'watch'
brew 'wget'
cask 'wireshark'
brew 'zsh'
