tap 'gapple/services' # Installs `brew services` commands
brew 'caskroom/cask/brew-cask' # Installs `brew cask` commands
tap 'caskroom/versions' # Alternate versions of casks

cask 'android-file-transfer'
brew 'awscli'
cask 'chefdk'
brew 'coreutils'
cask 'cyberduck'
cask 'flux'
brew 'git'
brew 'gnu-sed'
cask 'google-drive'
cask 'google-chrome'
cask 'iterm2'
brew 'jq'
brew 'mtr'
brew 'nmap'
brew 'pssh'
brew 'python3'
#brew 'rbenv'
brew 'rename'
#brew 'ruby-build'
brew 'shellcheck'
cask 'sublime-text3'
brew 'the_silver_searcher'
cask 'vlc'
brew 'watch'
brew 'wget'
cask 'wireshark'
cask 'xquartz'
