provisioner:
  http_proxy: <%= ENV['VAGRANT_HTTP_PROXY'] %>
  https_proxy: <%= ENV['VAGRANT_HTTPS_PROXY'] %>
  chef_omnibus_url: http://www.chef.io/chef/install.sh
driver:
  synced_folders:
    - ['.', '/host', 'create: true']
